spring.application.name=award-api

spring.datasource.url=jdbc:h2:mem:awarddb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.main.banner-mode=off
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.open-in-view=false
